# Generated by Django 6.0.7 on 2026-07-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_provider', models.CharField(choices=[('ollama', 'Ollama (Local)'), ('google', 'Google Gemini'), ('openai', 'OpenAI')], default='ollama', max_length=20)),
                ('model_name', models.CharField(default='gemma4:latest', help_text='Exact model tag/name.', max_length=100)),
                ('context_window', models.IntegerField(default=8192, help_text='Context window size (num_ctx).')),
                ('temperature', models.FloatField(default=0.0, help_text='Model creativity level (0 = deterministic).')),
                ('target_db_path', models.CharField(default='storage/databases/construction_company.db', help_text='Local absolute or relative path to the target SQLite database to inspect.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
