# Generated by Django 6.0.7 on 2026-07-30 23:36

from django.db import migrations, models


def convert_system_to_light(apps, schema_editor):
    UserPreference = apps.get_model("settings_panel", "UserPreference")
    UserPreference.objects.filter(theme="system").update(theme="light")


def reverse_convert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('settings_panel', '0002_userpreference'),
    ]

    operations = [
        migrations.RunPython(convert_system_to_light, reverse_convert),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('ocean', 'Ocean'), ('matrix', 'Matrix'), ('sunset', 'Sunset'), ('blush', 'Blush'), ('synthwave', 'Synthwave'), ('graphite', 'Graphite')], default='light', max_length=20),
        ),
    ]
