# Generated by Django 6.0.7 on 2026-07-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_panel', '0003_alter_userpreference_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='font_family',
            field=models.CharField(choices=[('system', 'System UI'), ('serif', 'Serif'), ('mono', 'Monospace'), ('rounded', 'Rounded')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='font_size',
            field=models.CharField(choices=[('12px', '12px'), ('14px', '14px'), ('16px', '16px'), ('18px', '18px')], default='16px', max_length=4),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(choices=[('America/Mexico_City', 'CDMX (UTC-6)'), ('America/New_York', 'New York (UTC-5)'), ('America/Chicago', 'Chicago (UTC-6)'), ('America/Denver', 'Denver (UTC-7)'), ('America/Los_Angeles', 'Los Angeles (UTC-8)'), ('America/Argentina/Buenos_Aires', 'Buenos Aires (UTC-3)'), ('America/Sao_Paulo', 'São Paulo (UTC-3)'), ('Europe/Madrid', 'Madrid (UTC+1)'), ('Europe/London', 'London (UTC+0)'), ('Europe/Berlin', 'Berlin (UTC+1)'), ('Asia/Tokyo', 'Tokyo (UTC+9)'), ('Asia/Shanghai', 'Shanghai (UTC+8)'), ('Asia/Kolkata', 'India (UTC+5:30)'), ('Australia/Sydney', 'Sydney (UTC+10)'), ('Pacific/Auckland', 'Auckland (UTC+12)'), ('UTC', 'UTC')], default='America/Mexico_City', max_length=50),
        ),
    ]
