# Generated by Django 6.0.7 on 2026-07-31 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings_panel', '0004_userpreference_font_family_userpreference_font_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('ollama', 'Ollama')], max_length=20)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], max_length=10)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('model', models.CharField(default='gpt-4o', max_length=100)),
                ('temperature', models.FloatField(default=0.0)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_credentials', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Credential',
                'verbose_name_plural': 'LLM Credentials',
            },
        ),
        migrations.AddField(
            model_name='userpreference',
            name='active_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='settings_panel.llmprovidercredential'),
        ),
    ]
