# Generated by Django 6.0.7 on 2026-07-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title_edited',
            field=models.BooleanField(default=False),
        ),
    ]
